version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  tagit:
    image: ccs/tagit-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4376:4376"
    depends_on: 
      - redis
    volumes:
      - ./config/database/:/app/database/
      - ./config/media/:/app/media/
      - ./config/static/:/app/static/
    restart: always
