# Generated by Django 4.1.5 on 2023-02-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_QR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='url',
        ),
    ]
