# Generated by Django 4.1.5 on 2023-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_QR', '0002_remove_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='target',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
